library(photobiology)
oldwd <- setwd("~/Rpackages/photobiologyLamps/raw.data/Macam/UV_lamps")
qpanel.uvb313.data <- read.csv(file="Q-Panel_UVB-313.csv", skip=2, header=FALSE, col.names=c("w.length", "s.e.irrad"), nrows=561)
qpanel.uvb313.data$s.q.irrad <- with(qpanel.uvb313.data, as_quantum_mol(w.length, s.e.irrad))
head(qpanel.uvb313.data); tail(qpanel.uvb313.data)
save(qpanel.uvb313.data, file="~/Rpackages/photobiologyLamps/data/qpanel.uvb313.data.rda")
qpanel.uva340.data <- read.csv(file="Q-Panel_UVA-340.csv", skip=2, header=FALSE, col.names=c("w.length", "s.e.irrad"), nrows=561)
qpanel.uva340.data$s.q.irrad <- with(qpanel.uva340.data, as_quantum_mol(w.length, s.e.irrad))
head(qpanel.uva340.data); tail(qpanel.uva340.data)
save(qpanel.uva340.data, file="~/Rpackages/photobiologyLamps/data/qpanel.uva340.data.rda")
philips.tl12.data <- read.csv(file="Philips_TL12.csv", skip=2, header=FALSE, col.names=c("w.length", "s.e.irrad"), nrows=561)
philips.tl12.data$s.q.irrad <- with(philips.tl12.data, as_quantum_mol(w.length, s.e.irrad))
head(philips.tl12.data); tail(philips.tl12.data)
save(philips.tl12.data, file="~/Rpackages/photobiologyLamps/data/philips.tl12.data.rda")
setwd(oldwd)
plot(s.e.irrad ~ w.length, data=qpanel.uvb313.data, type="l")
plot(s.e.irrad ~ w.length, data=qpanel.uvb313.data, type="l", log="y")
plot(I(s.q.irrad * 1e6) ~ w.length, data=qpanel.uvb313.data, type="l")
plot(I(s.q.irrad * 1e6) ~ w.length, data=qpanel.uvb313.data, type="l", log="y")
plot(s.e.irrad ~ w.length, data=qpanel.uva340.data, type="l")
plot(s.e.irrad ~ w.length, data=qpanel.uva340.data, type="l", log="y")
plot(I(s.q.irrad * 1e6) ~ w.length, data=qpanel.uva340.data, type="l")
plot(I(s.q.irrad * 1e6) ~ w.length, data=qpanel.uva340.data, type="l", log="y")
plot(s.e.irrad ~ w.length, data=philips.tl12.data, type="l")
plot(s.e.irrad ~ w.length, data=philips.tl12.data, type="l", log="y")
plot(I(s.q.irrad * 1e6) ~ w.length, data=philips.tl12.data, type="l")
plot(I(s.q.irrad * 1e6) ~ w.length, data=philips.tl12.data, type="l", log="y")
